name: Build and Release

on:
  push:
    branches: [ v3,v2 ] # 只在提交到2.0分支时触发
  workflow_dispatch:
env:
  APP_NAME: simple_sq_music_plus_web
  DOCKER_IMAGE_NAME: simple_sq_music_plus_web

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=v$VERSION" >> $GITHUB_ENV

      - name: Set version from input if provided
        if: ${{ github.event.inputs.release_version != '' }}
        run: |
          echo "VERSION=${{ github.event.inputs.release_version }}" >> $GITHUB_ENV

      - name: Zip build artifacts
        run: |
          cd dist
          zip -r ../${{ env.APP_NAME }}.zip .
          cd ..

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false
          files: |
            ${{ env.APP_NAME }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Alibaba Cloud Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push base Docker image to Alibaba Cloud
        run: |
          docker version
          # 构建基础架构镜像（默认平台）
          docker buildx build . \
            --file Dockerfile \
            --tag registry.cn-hangzhou.aliyuncs.com/sqdockler/simple_sq_music_plus_web:${{ env.VERSION }} \
            --push
          # 构建 latest 标签
          docker buildx build . \
            --file Dockerfile \
            --tag registry.cn-hangzhou.aliyuncs.com/sqdockler/simple_sq_music_plus_web:latest \
            --push

      - name: Build and push AMD64 Docker image to Alibaba Cloud
        run: |
          docker version
          # 构建 AMD64 架构镜像
          docker buildx build . \
            --platform linux/amd64 \
            --file Dockerfile \
            --tag registry.cn-hangzhou.aliyuncs.com/sqdockler/simple_sq_music_plus_web:${{ env.VERSION }}-amd64 \
            --push

      - name: Build and push ARM64 Docker image to Alibaba Cloud
        run: |
          docker version
          # 构建 ARM64 架构镜像
          docker buildx build . \
            --platform linux/arm64 \
            --file Dockerfile \
            --tag registry.cn-hangzhou.aliyuncs.com/sqdockler/simple_sq_music_plus_web:${{ env.VERSION }}-arm64 \
            --push
          # 构建 ARM64 架构 latest 标签
          docker buildx build . \
            --platform linux/arm64 \
            --file Dockerfile \
            --tag registry.cn-hangzhou.aliyuncs.com/sqdockler/simple_sq_music_plus_web:latest-arm64 \
            --push

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push base Docker image to GitHub Packages
        run: |
          docker version
          # 构建基础架构镜像（默认平台）
          docker buildx build . \
            --file Dockerfile \
            --tag ghcr.io/${{ github.actor }}/simple_sq_music_plus_web:${{ env.VERSION }} \
            --push
          # 构建 latest 标签
          docker buildx build . \
            --file Dockerfile \
            --tag ghcr.io/${{ github.actor }}/simple_sq_music_plus_web:latest \
            --push

      - name: Build and push AMD64 Docker image to GitHub Packages
        run: |
          docker version
          # 构建 AMD64 架构 Docker 镜像
          docker buildx build . \
            --platform linux/amd64 \
            --file Dockerfile \
            --tag ghcr.io/${{ github.actor }}/simple_sq_music_plus_web:${{ env.VERSION }}-amd64 \
            --push

      - name: Build and push ARM64 Docker image to GitHub Packages
        run: |
          docker version
          # 构建 ARM64 架构 Docker 镜像
          docker buildx build . \
            --platform linux/arm64 \
            --file Dockerfile \
            --tag ghcr.io/${{ github.actor }}/simple_sq_music_plus_web:${{ env.VERSION }}-arm64 \
            --push
          # 构建 ARM64 架构 latest 标签
          docker buildx build . \
            --platform linux/arm64 \
            --file Dockerfile \
            --tag ghcr.io/${{ github.actor }}/simple_sq_music_plus_web:latest-arm64 \
            --push
